Initialisation Terminée
WildCodeSchool-2024-02/php-poec-paris-p2-bills pull request #2
Opened 2024-05-29 14:45 UTC by Youssef750XX

_ Clean Code Base
_ database.sql
_ New readme

2024-05-29 14:46 UTC, IreneB21 approved these changes

2024-05-30 12:33 UTC, mickaellambert requested changes

2024-05-30 12:33 UTC, mickaellambert commented on database.sql
> +CREATE TABLE `user` (
Ne pas mettre le préfixe ou suffixe "user", on est déjà dans la table user

2024-05-30 12:33 UTC, mickaellambert commented on database.sql
> +    `id_user` INT NOT NULL,
Ici, la clé étrangère doit s'appeler "user_id"

2024-05-30 12:33 UTC, mickaellambert commented on database.sql
> +    `due_date` DATE NOT NULL,
due_at ?

2024-05-30 12:33 UTC, mickaellambert commented on database.sql
> +    `id_invoice` INT NOT NULL,
"invoice_id"

2024-05-30 12:33 UTC, mickaellambert commented on database.sql
> +    `product_name` VARCHAR(255) NOT NULL,
pas besoin de préfixe "product_" ici

2024-05-30 12:40 UTC, mickaellambert approved these changes

2024-05-30 12:40 UTC, merged