Fix Database
WildCodeSchool-2024-02/php-poec-paris-p2-bills pull request #3
Opened 2024-06-05 16:10 UTC by Youssef750XX

Table invoice : Ajout des informations de l'utilisateur

Table product : Ajout de la ligne total

Général : Ajout de "ON DELETE CASCADE" afin de respecter l'intégrité de la BDD.

2024-06-05 17:41 UTC, IreneB21 approved these changes

2024-06-05 20:59 UTC, mickaellambert requested changes

2024-06-05 20:59 UTC, mickaellambert commented on database.sql
> +    `total` DECIMAL(10,2) NOT NULL,
Pas trop d'accord avec cette donnée qui peut être facilement calculé via le quantité et le prix

2024-06-06 10:57 UTC, Youssef750XX commented on database.sql
> +    `total` DECIMAL(10,2) NOT NULL,
Je ne comprends pas la demande. Tu souhaites que je retire cette colone de la table ou tu veux que j'effectue les operations côté serveur et/ou côté front ?

2024-06-06 13:20 UTC, merged